name: Push Docker image to Registry

on:
  workflow_call:
    inputs:
      docker_image_name:
        required: true
        type: string
      docker_image_artifact_name:
        required: true
        type: string
      docker_image_artifact_object_name:
          required: true
          type: string

jobs:
  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      # load previously build docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.docker_image_artifact_name }}
          path: /tmp
      - name: Load docker image
        run: |
          docker load --input /tmp/${{ inputs.docker_image_artifact_object_name }}.tar
          docker image ls -a

      # login to container registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to JFrog
        uses: docker/login-action@v1
        with:
          registry: oltho.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_ACCESS_TOKEN }}

      # pushing docker image
      - name: push docker image to GHCR
        run: |
          docker tag ${{ inputs.docker_image_name }} ${{ env.GHCR_IMAGE_URL }}
          docker push ${{ env.GHCR_IMAGE_URL }}
        env:
          GHCR_IMAGE_URL: ghcr.io/oltho/${{ inputs.docker_image_name }}
      - name: push docker image to JFROG
        run: |
          docker tag ${{ inputs.docker_image_name }} ${{ env.JFROG_IMAGE_URL }}
          docker push ${{ env.JFROG_IMAGE_URL }}
        env:
          JFROG_IMAGE_URL: oltho.jfrog.io/default-docker-local/${{ inputs.docker_image_name }}
